### ISSUE TITLE
[DataCap Application] <The Second Life> - <3D-printed>

### ISSUE THREAD

**Issue by AlterEgogo** [py-guazi/GZ-FIP0078-Pathway#5]
### Data Owner Name

The Second Life

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://mp.weixin.qq.com/s/IMtL_m4sQAxqCmNWlw28Gw

### Social Media Handle

https://mp.weixin.qq.com/s/IMtL_m4sQAxqCmNWlw28Gw

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

300TiB

### Number of replicas to store

7

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1iyihonsjs44ke5ftorilthinv22s3bjvzkv2v3i

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Second Life Universe Block is a digital hipster block with 3D printing and digital twins as the underlying technology, and a collection of 3D-printed real-life artefacts, 3D-printed coffee, and meta-universe experiences. Embrace the future, private ordering, self-realisation, and one-click construction of the second life of real human beings.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
For each 3D printed model, we need to take high-precision photos of the 360-degree panorama. The production photos for one model are up to tens of thousands of photos, and we will model the model in 3D. We need to store these photos, models and other data
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We currently store our data on our own work computers, and on servers in the server room. In the case of data from the computers we will transfer it over the network, and in the case of data from the server we can do hard drive mailing
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have not previously stored on an IPFS network and the cost of storing on an IPFS network will make it much cheaper for us to do business.SP's information is something we are currently in contact with on an ongoing basis, and I will disclose it below in the request form.
```

### Please share a sample of the data

```text
You can check out the WeChat video number, the name of the account is "第二人生3D真人手办".
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03079511 HK；
f02327534 US；
f02894855 CHINA；
f02826234 SG
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by AlterEgogo** [comment]
@Fatman13 
Thanks for the reply, have arranged for a colleague to send an email, please check. Thank you.

**Comment by Fatman13** [comment]
> Thanks for the reply, have arranged for a colleague to send an email, please check. Thank you.

Thank you! I see that you have updated data type. Could you please send more sample data for evaluation? We are open to sign NDAs to protect your privacy.

**Comment by AlterEgogo** [comment]
@Fatman13 Ok, I have attached our business licence to the email so you can check it out! Thank you！

**Comment by Fatman13** [comment]
LGTM! Will approve. Please remember to follow allocator distribution rules specified in [here](https://github.com/filecoin-project/notary-governance/issues/1023). Thank you!

**Comment by AlterEgogo** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
Distribution looks okay from the CID checker report.

**Comment by AlterEgogo** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
Hello, dear applicant, from the CID report, i see that there is CID sharing is observed by the bot. Is there a mixed happened during distribution?

**Comment by AlterEgogo** [comment]
@Fatman13
From the sharing records it is seen that there are data sharing LDNs as far back as 2022, unfortunately and apologetically we did not find a data sharing issue after querying the issue with the data. This is because we were not able to download the data from another LDN for comparison. The only possible explanation for the data consistency issue is that the 32 gigabytes of data may have been sourced from public data by both us and the company.

**Comment by Fatman13** [comment]
Got it. Thank you!

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger
